[default]
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
TITLE = "FlaskFAQ"
SECRET_KEY = "54d08d8e-2107-496e-9a4b-451dc9905d6e"

[development]
SQLALCHEMY_DATABASE_URI = "sqlite:///flask.db"
FLASK_ADMIN_NAME = "Admin FAQ (Dev)"

[production]
SESSION_COOKIE_DOMAIN = true